name: Type check
on:
  push:
jobs:
  typeCheck:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8

      - name: Install project dependencies
        run: pnpm install

      - name: Check type system
        # If TypeScript project references is set up properly, `tsc --build` should work right after dependencies
        # has been installed, no extra build/compile step required
        id: typeCheckModules
        run: pnpm check:types
        env:
          NODE_OPTIONS: --max_old_space_size=8192
